resource_group_name = "ai-lz-rg-prod"
location            = "westus2"
vnet_name           = "ai-lz-vnet-prod"
vnet_address_space  = "192.168.20.0/23"
enable_telemetry    = false
ai_foundry_purge_on_destroy = false
ai_foundry_create_agent_service = true
ai_model_name = "gpt-4.1-prod"
ai_model_format = "OpenAI"
ai_model_version = "2025-04-14"
ai_model_scale_type = "GlobalStandard"
ai_model_scale_capacity = 3

ai_project_name = "project-prod"
ai_project_description = "AI Project for Production Environment"
ai_project_display_name = "AI Production Project"
ai_project_create_connections = true

app_gateway_deploy = false
app_gateway_backend_pool_name = "prod-backend-pool"
app_gateway_http_settings_name = "prod-http-settings"
app_gateway_http_settings_port = 443
app_gateway_http_settings_protocol = "Https"
app_gateway_frontend_port_name = "prod-frontend-port"
app_gateway_frontend_port = 443
app_gateway_listener_name = "prod-listener"
app_gateway_rule_name = "prod-rule"
app_gateway_rule_type = "Basic"
app_gateway_rule_priority = 100
